openapi: '3.0.2'
info:
  title: ARC Core Api
  version: '1.0'
servers:
  - url: http://example.com
paths:
  /core/resolveAccess:
    get:
      parameters:
        - in: header  
          name: security
          schema:
            type: string
          required: true
        - in: header
          name: arc-account-id
          schema:
             type: string     
        - in: query
          name: serviceId
          schema:
            type: string
        - in: query
          name: resourceId
          schema:
            type: string
        - in: query
          name: accountName
          schema:
            type: string
      responses:
        '200':
           description: OK
        '403':
           description: access denied
        '204':
           description: no iam policy defined for the resource.
        '404': 
           description: resource not found    
        '400':
           description: bad request
  /core/getPolicy:        
        get: 
          parameters:
            - in: header 
              name: security
              schema:
                type: string
              required: true
            - in: header
              name: arc-account-id
              schema:
                type: string    
              required: true
            - in: query 
              name: policyId
              schema:
                type: string 
              required: true  
          responses:
            '200':
              description: OK
              content:
                application/json:
                  schema:
                    $ref:  '#/components/schemas/PolicyDocuments'
                
            '403':
              description: access denied
            '404': 
              description: resource not found , passed policy id does not exist.    
            '400':
              description: bad request          
  #/core/addPolicyRule:


components:
    schemas:
      PolicyDocuments:
        type: object
        properties:
          id: 
            type: string
          name:
            type: string
          description:
            type: string
          accountId:
            type: string
          policyType:
            type: string
            enum: ["identity","resource"]
          version:
            type: object
            properties:
              version:
                type: string
              versionNo: 
                type: string
              updatedBy:
                type: string
              updatedAt:
                type: string
          rules: 
            type: array
            items: 
              $ref: '#/components/schemas/SimpleRule'
      SimpleRule:
           type: object
           properties:
             ruleType: 
                type: string
                enum: ["SIMPLE",INHERIT]
             resourceCategory:
                type: string
             effect:
                type: string
             actions:
                type: string
             resources:
                type: array
                items:
                    type: string
             conditions:
              type: object    

          





  
